In [1]:
(ls_file <- list.files("digitiser_csv", full.names = TRUE))

 [1] "digitiser_csv/005-941.csv" "digitiser_csv/005-942.csv"
 [3] "digitiser_csv/005-943.csv" "digitiser_csv/005-944.csv"
 [5] "digitiser_csv/005-945.csv" "digitiser_csv/005-946.csv"
 [7] "digitiser_csv/005-947.csv" "digitiser_csv/005-948.csv"
 [9] "digitiser_csv/005-949.csv" "digitiser_csv/005-950.csv"
[11] "digitiser_csv/005-951.csv" "digitiser_csv/005-952.csv"
[13] "digitiser_csv/005-953.csv" "digitiser_csv/005-954.csv"
[15] "digitiser_csv/005-955.csv" "digitiser_csv/005-956.csv"
[17] "digitiser_csv/005-957.csv" "digitiser_csv/005-958.csv"
[19] "digitiser_csv/005-959.csv" "digitiser_csv/005-960.csv"
[21] "digitiser_csv/005-961.csv" "digitiser_csv/005-962.csv"
[23] "digitiser_csv/005-963.csv" "digitiser_csv/005-964.csv"
[25] "digitiser_csv/005-965.csv" "digitiser_csv/005-966.csv"
[27] "digitiser_csv/005-967.csv"

In [3]:
get_digitiser <- function(csv_file){

    read.csv(csv_file) |>
    
 
}

In [6]:
get_digitiser(ls_file[1]) |>  head()

  sample_id Particle.Diameter..µm. Volume.Frequency.Percent
1 T1SG1     0.4493990              0.00000
2 T1SG1     0.4760276              0.00744
3 T1SG1     0.5042340              0.02804
4 T1SG1     0.5341117              0.06480
5 T1SG1     0.5657598              0.11766
6 T1SG1     0.5992832              0.18324
  Particle.Diameter..µm..1 Cumulative.Finer.Volume.Percent
1 0.4366486                0.00000
2 0.4625217                0.00000
3 0.4899278                0.00744
4 0.5189579                0.03548
5 0.5497080                0.10028
6 0.5822803                0.21794

In [ ]:
#  approx(x = df$diameter, y = df$cumulative, xout = cutoff)$y

In [ ]:
#http://localhost:8889/lab?token=f7562502286cdae70c1998a8885098375951a20cf48620a3

In [12]:
#do.call(rbind, 
lapply( read.csv(ls_file[1])

    sample_id Particle.Diameter..µm. Volume.Frequency.Percent
1   T1SG1     0.4493990              0.00000
2   T1SG1     0.4760276              0.00744
3   T1SG1     0.5042340              0.02804
4   T1SG1     0.5341117              0.06480
5   T1SG1     0.5657598              0.11766
6   T1SG1     0.5992832              0.18324
7   T1SG1     0.6347930              0.25504
8   T1SG1     0.6724068              0.32445
9   T1SG1     0.7122494              0.38208
10  T1SG1     0.7544528              0.41978
11  T1SG1     0.7991570              0.43267
12  T1SG1     0.8465100              0.42061
13  T1SG1     0.8966689              0.38892
14  T1SG1     0.9497998              0.34764
15  T1SG1     1.0060790              0.30955
16  T1SG1     1.0656930              0.28708
17  T1SG1     1.1288392              0.28923
18  T1SG1     1.1957272              0.31836
19  T1SG1     1.2665785              0.36904
20  T1SG1     1.3416279              0.42912
21  T1SG1     1.4211244              0.48359
22  T1SG1     1.5053313              0.52002
23  T1SG1     1.5945278              0.53385
24  T1SG1     1.6890095              0.53057
25  T1SG1     1.7890896              0.52354
26  T1SG1     1.8950998              0.52737
27  T1SG1     2.0073916              0.55057
28  T1SG1     2.1263370              0.59142
29  T1SG1     2.2523304              0.64006
30  T1SG1     2.3857894              0.68529
⋮   ⋮         ⋮                      ⋮
91  T1SG1      79.91570              0.666570
92  T1SG1      84.65100              0.608050
93  T1SG1      89.66689              0.556930
94  T1SG1      94.97998              0.525300
95  T1SG1     100.60790              0.524510
96  T1SG1     106.56930              0.559660
97  T1SG1     112.88392              0.625320
98  T1SG1     119.57272              0.705330
99  T1SG1     126.65785              0.776930
100 T1SG1     134.16279              0.818130
101 T1SG1     142.11244              0.815960
102 T1SG1     150.53313              0.771470
103 T1SG1     159.45278              0.700770
104 T1SG1     168.90095              0.632740
105 T1SG1     178.90896              0.604800
106 T1SG1     189.50998              0.656730
107 T1SG1     200.73916              0.822180
108 T1SG1     212.63370              1.119490
109 T1SG1     225.23304              1.545490
110 T1SG1     238.57894              2.072780
111 T1SG1     252.71563              2.649930
112 T1SG1     267.68997              3.205200
113 T1SG1     283.55160              3.654970
114 T1SG1     300.35308              3.916370
115 T1SG1     318.15012              3.922340
116 T1SG1     337.00170              3.634288
117 T1SG1     356.97031              3.049485
118 T1SG1     378.12213              2.201359
119 T1SG1     400.52727              1.154958
120 T1SG1     424.26001              0.000000
    Particle.Diameter..µm..1 Cumulative.Finer.Volume.Percent
1   0.4366486                 0.00000
2   0.4625217                 0.00000
3   0.4899278                 0.00744
4   0.5189579                 0.03548
5   0.5497080                 0.10028
6   0.5822803                 0.21794
7   0.6167826                 0.40118
8   0.6533292                 0.65622
9   0.6920414                 0.98067
10  0.7330475                 1.36275
11  0.7764833                 1.78253
12  0.8224928                 2.21520
13  0.8712285                 2.63581
14  0.9228521                 3.02473
15  0.9775345                 3.37237
16  1.0354571                 3.68192
17  1.0968118                 3.96900
18  1.1618019                 4.25823
19  1.2306430                 4.57659
20  1.3035632                 4.94563
21  1.3808042                 5.37475
22  1.4626220                 5.85834
23  1.5492878                 6.37836
24  1.6410889                 6.91221
25  1.7383295                 7.44278
26  1.8413320                 7.96632
27  1.9504378                 8.49369
28  2.0660085                 9.04426
29  2.1884272                 9.63568
30  2.3180996                10.27574
⋮   ⋮                        ⋮
91   77.64833                 56.50196
92   82.24928                 57.16853
93   87.12285                 57.77658
94   92.28521                 58.33351
95   97.75345                 58.85881
96  103.54571                 59.38332
97  109.68118                 59.94298
98  116.18019                 60.56830
99  123.06430                 61.27363
100 130.35632                 62.05056
101 138.08042                 62.86869
102 146.26220                 63.68465
103 154.92878                 64.45612
104 164.10889                 65.15689
105 173.83295                 65.78963
106 184.13320                 66.39443
107 195.04378                 67.05116
108 206.60085                 67.87334
109 218.84272                 68.99283
110 231.80996                 70.53832
111 245.54557                 72.61110
112 260.09506                 75.26103
113 275.50666                 78.46623
114 291.83145                 82.12120
115 309.12355                 86.03757
116 327.44027                 89.95991
117 346.84233                 93.59420
118 367.39403                 96.64368
119 389.16350                 98.84504
120 412.22288                100.00000